# Site settings
title: RESTier
email: odatafeedback@microsoft.com
description: > # this means to ignore newlines until "baseurl:"
  This site contains samples covering basic and advanced OData scenarios for
  OData Web API.
baseurl: "/Doc" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  odata

permalink: /:title/

# Build settings
kramdown:
  input: GFM
